import { Template } from '../types/theme';

export const TEMPLATES: Template[] = [
  {
    id: 'modern-blue',
    name: 'Hiện Đại Xanh',
    description: 'Thiết kế hiện đại với gam màu xanh dương chuyên nghiệp',
    category: 'modern',
    previewImage: '/templates/modern-blue.jpg',
    isPremium: false,
    config: {
      id: 'modern-blue',
      name: 'Modern Blue',
      colors: {
        primary: '#3B82F6',
        secondary: '#1E40AF',
        accent: '#F59E0B',
        background: '#FFFFFF',
        surface: '#F8FAFC',
        text: '#1F2937',
        textSecondary: '#6B7280',
        border: '#E5E7EB',
      },
      typography: {
        fontFamily: 'Inter',
        headingFont: 'Inter',
        sizes: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
        },
      },
      layout: {
        borderRadius: '0.75rem',
        spacing: 'normal',
        cardStyle: 'shadow',
        headerStyle: 'modern',
      },
    },
  },
  {
    id: 'traditional-red',
    name: 'Truyền Thống Đỏ',
    description: 'Phong cách truyền thống Việt Nam với màu đỏ may mắn',
    category: 'traditional',
    previewImage: '/templates/traditional-red.jpg',
    isPremium: false,
    config: {
      id: 'traditional-red',
      name: 'Traditional Red',
      colors: {
        primary: '#DC2626',
        secondary: '#B91C1C',
        accent: '#F59E0B',
        background: '#FEF2F2',
        surface: '#FFFFFF',
        text: '#1F2937',
        textSecondary: '#6B7280',
        border: '#FCA5A5',
      },
      typography: {
        fontFamily: 'Playfair Display',
        headingFont: 'Playfair Display',
        sizes: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
        },
      },
      layout: {
        borderRadius: '0.375rem',
        spacing: 'comfortable',
        cardStyle: 'border',
        headerStyle: 'classic',
      },
    },
  },
  {
    id: 'artistic-purple',
    name: 'Nghệ Thuật Tím',
    description: 'Thiết kế sáng tạo cho các nghệ nhân nghệ thuật',
    category: 'artistic',
    previewImage: '/templates/artistic-purple.jpg',
    isPremium: false,
    config: {
      id: 'artistic-purple',
      name: 'Artistic Purple',
      colors: {
        primary: '#7C3AED',
        secondary: '#5B21B6',
        accent: '#F59E0B',
        background: '#FAFAF9',
        surface: '#F9FAFB',
        text: '#1F2937',
        textSecondary: '#6B7280',
        border: '#D1D5DB',
      },
      typography: {
        fontFamily: 'Poppins',
        headingFont: 'Playfair Display',
        sizes: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
        },
      },
      layout: {
        borderRadius: '1rem',
        spacing: 'relaxed',
        cardStyle: 'elevated',
        headerStyle: 'artistic',
      },
    },
  },
  {
    id: 'minimal-gray',
    name: 'Tối Giản Xám',
    description: 'Thiết kế tối giản, tập trung vào nội dung',
    category: 'minimal',
    previewImage: '/templates/minimal-gray.jpg',
    isPremium: false,
    config: {
      id: 'minimal-gray',
      name: 'Minimal Gray',
      colors: {
        primary: '#374151',
        secondary: '#1F2937',
        accent: '#059669',
        background: '#FFFFFF',
        surface: '#F9FAFB',
        text: '#111827',
        textSecondary: '#6B7280',
        border: '#E5E7EB',
      },
      typography: {
        fontFamily: 'System UI',
        headingFont: 'System UI',
        sizes: {
          xs: '0.75rem',
          sm: '0.875rem',
          base: '1rem',
          lg: '1.125rem',
          xl: '1.25rem',
          '2xl': '1.5rem',
          '3xl': '1.875rem',
        },
      },
      layout: {
        borderRadius: '0.25rem',
        spacing: 'compact',
        cardStyle: 'flat',
        headerStyle: 'minimal',
      },
    },
  },
];

export const COLOR_PRESETS = [
  {
    name: 'Xanh Dương Chuyên Nghiệp',
    primary: '#3B82F6',
    secondary: '#1E40AF',
  },
  { name: 'Đỏ Truyền Thống', primary: '#DC2626', secondary: '#B91C1C' },
  { name: 'Tím Nghệ Thuật', primary: '#7C3AED', secondary: '#5B21B6' },
  { name: 'Xanh Lá Tự Nhiên', primary: '#059669', secondary: '#047857' },
  { name: 'Cam Sáng Tạo', primary: '#EA580C', secondary: '#C2410C' },
  { name: 'Hồng Dịu Dàng', primary: '#EC4899', secondary: '#BE185D' },
];

export const FONT_OPTIONS = [
  { name: 'Inter (Hiện đại)', value: 'Inter', category: 'modern' },
  {
    name: 'Playfair Display (Thanh lịch)',
    value: 'Playfair Display',
    category: 'elegant',
  },
  { name: 'Poppins (Thân thiện)', value: 'Poppins', category: 'friendly' },
  { name: 'Roboto (Đơn giản)', value: 'Roboto', category: 'simple' },
  { name: 'Lora (Cổ điển)', value: 'Lora', category: 'classic' },
  { name: 'Montserrat (Hiện đại)', value: 'Montserrat', category: 'modern' },
];

export const LAYOUT_OPTIONS = [
  {
    name: 'Hiện đại',
    value: 'modern',
    description: 'Bo góc mềm mại, spacing rộng rãi',
    borderRadius: '0.75rem',
    spacing: 'normal',
    cardStyle: 'shadow' as const,
  },
  {
    name: 'Cổ điển',
    value: 'classic',
    description: 'Phong cách truyền thống, đường viền rõ ràng',
    borderRadius: '0.375rem',
    spacing: 'comfortable',
    cardStyle: 'border' as const,
  },
  {
    name: 'Tối giản',
    value: 'minimal',
    description: 'Đơn giản, tập trung vào nội dung',
    borderRadius: '0.25rem',
    spacing: 'compact',
    cardStyle: 'flat' as const,
  },
  {
    name: 'Nghệ thuật',
    value: 'artistic',
    description: 'Sáng tạo, bố cục linh hoạt',
    borderRadius: '1rem',
    spacing: 'relaxed',
    cardStyle: 'elevated' as const,
  },
];
